export {
  MacOsPlatformAdapter,
  MacOsPlatformDiscoveryError,
  MacOsPlatformTrustError,
  MacOsPlatformInputError,
  MacOsPlatformUnsupportedError,
} from "./macos.js";
export type {
  MacOsPlatformAdapterOptions,
  MacOsPlatformEnvironment,
} from "./macos.js";
export { DARWIN_SYSTEM_EXECUTABLES, inspectSystemPath, inspectSystemPathSync } from "./system-executables.js";
export type {
  AgentDiscovery,
  AgentName,
  PlatformAdapter,
  PlatformFacts,
} from "./types.js";
export {
  MacOsRetainedRename,
  MacOsRetainedRenameRefusalError,
  MacOsRetainedRenameThirdStateError,
  MacOsRetainedRenameUnavailableError,
  SpawnRenameAtxRunner,
} from "./retained-rename.js";
export type {
  ExactNoReplaceRenameRequestV1,
  ExactRenameParentIdentityV1,
  MacOsRetainedRenameDependencies,
  RenameNoReplace,
  RenameAtxRunner,
  RenameAtxRunRequestV1,
  RenameAtxRunResultV1,
  RenameSameParentNoReplace,
} from "./retained-rename.js";
export {
  admitLauncherPlatformIdentity,
  LauncherBundleAdmission,
  LauncherBundleRecoveryRequiredError,
  LauncherPlatformUnsupportedError,
} from "./launcher/index.js";
export type {
  AdmittedReleaseBundleV1,
  LauncherBundleAdmissionRequestV1,
  LauncherGuardedReaderV1,
  LauncherPlatformIdentityV1,
} from "./launcher/index.js";
export { MacOsStableLockProvider } from "./stable-lock.js";
export type {
  MacOsStableLockDependencies,
  MacOsStableLockFileSystem,
} from "./stable-lock.js";
export {
  EX_TEMPFAIL,
  MacOsTransactionLockOperationalError,
  MacOsTransactionLockProvider,
  MacOsTransactionLockUnavailableError,
  SpawnLockfRunner,
} from "./transaction-lock.js";
export type { LockfResult, LockfRunner } from "./transaction-lock.js";
export {
  LAUNCHD_JOBS,
  LaunchdInputError,
  MAX_LAUNCHD_PLIST_BYTES,
  boundedCanonicalPlistXml,
  buildLaunchdPlanPreview,
  eligibleLaunchdJobs,
  encodeLaunchdPlist,
  encodeRetainedLaunchdPlist,
  generatedLabel,
  gitSyncEligible,
  launchdCalendarInterval,
  launchdGeneration,
  launchdGuiDomain,
  launchdJob,
  launchdLogPath,
  launchdPlistDictionary,
  launchdPlistPath,
  launchdPriorStateFingerprint,
  launchdStatusPath,
  parseGeneratedLabel,
  parseScheduleFlag,
  parseScheduledProductHome,
  reconcileAutomationSchedules,
  scheduledArgvParts,
  scheduledBaseArgv,
  scheduledProgramArguments,
} from "./launchd/index.js";
export type {
  BoundedCanonicalPlistXmlV1,
  ClosedLaunchdBaseLabelV1,
  GeneratedLaunchdLabelV1,
  LaunchdBaseArgvV1,
  LaunchdCalendarIntervalV1,
  LaunchdGeneratedServiceTargetV1,
  LaunchdGenerationProjectionV1,
  LaunchdGenerationV1,
  LaunchdGuiDomainV1,
  LaunchdJobDefinitionV1,
  LaunchdLiveStateV1,
  LaunchdObservedLabelV1,
  LaunchdObservedServiceTargetV1,
  LaunchdPlanOperationV1,
  LaunchdPlanPreviewEntryV1,
  LaunchdPlanPreviewV1,
  LaunchdPlistDictionaryV1,
  LaunchdPreviewRequestV1,
  LaunchdPriorJobStateV1,
  LaunchdLegacyProgramArgumentsV1,
  LaunchdProgramArgumentsV1,
  LaunchdScheduledProductHomeV1,
} from "./launchd/index.js";
export {
  LAUNCHD_PREVIEW_OBSERVATION_TABLE,
  LAUNCHD_PROCESS_PATH,
  LAUNCHD_DISTRIBUTION_POLICY,
  LAUNCHD_SERVICE_ABSENT_EXIT,
  LaunchdDistributionUnsupportedError,
  LaunchdObserver,
  SUPPORTED_LAUNCHD_PROCESS_TABLE_TEMPLATE,
  admitLaunchdHost,
  deslotLaunchdProcessTable,
  expandLaunchdProcessTable,
  launchdObservationProcessTableHash,
  launchdProcessTableHash,
  launchdProcessTableTemplateHash,
  recheckLaunchdHost,
  requireLaunchdMutationTable,
} from "./launchd/index.js";
export type {
  LaunchctlIdentityV1,
  LaunchdArgvSlotV1,
  LaunchdBootoutArgvV1,
  LaunchdBootstrapArgvV1,
  LaunchdDistributionPolicyV2,
  LaunchdEmptyDirectoryIdentityV1,
  LaunchdEmptyDirectoryObservationV1,
  LaunchdExecutablePolicyV1,
  LaunchdHostObserverV1,
  LaunchdLiveObservationV1,
  LaunchdMutationIoProfileV1,
  LaunchdObservationDependenciesV1,
  LaunchdObservationJobV1,
  LaunchdObservationRequestV1,
  LaunchdObservedStateV1,
  LaunchdOperatingSystemPolicyV1,
  LaunchdPreviewObservationProcessTableV1,
  LaunchdProbeDomainArgvV1,
  LaunchdProbeServiceArgvV1,
  LaunchdProcessArgvV1,
  LaunchdProcessDirectoryIdentityV1,
  LaunchdProcessDirectorySlotV1,
  LaunchdProcessEnvironmentV1,
  LaunchdProcessIoProfileV1,
  LaunchdQueryIoProfileV1,
  LaunchdUnobservableReasonV1,
  SupportedLaunchdProcessTableTemplateV1,
  SupportedLaunchdProcessTableV1,
} from "./launchd/index.js";
export { LaunchdPathBootstrapper, parseLaunchctlPrintedService } from "./launchd/index.js";
export type {
  LaunchdBootstrapDependenciesV1,
  LaunchdBootstrapDirectionV1,
  LaunchdBootstrapPlistIdentityV1,
  LaunchdBootstrapRequestV1,
  LaunchdBootstrapRoleV1,
  LaunchdFileHandleV1,
  LaunchdFileSystemV1,
  LaunchdMutationEvidenceV1,
  LaunchdOpenedPlistIdentityV1,
  LaunchdPrintedServiceV1,
} from "./launchd/index.js";
export {
  LAUNCHD_EFFECT_JOURNAL_PHASES,
  LAUNCHD_EFFECT_LEDGER_CODEC,
  LAUNCHD_PLAN_CODEC,
  LAUNCHD_PLAN_PREVIEW_CODEC,
  LaunchdBootoutRunner,
  LaunchdEffectExecutor,
  LaunchdEffectJournalStore,
  NodeLaunchdPlistReader,
  assertLaunchdPlan,
  assertLaunchdPlanBindings,
  encodeLaunchdEffectJournal,
  encodeLaunchdEffectPlan,
  launchdEffectPlan,
  launchdEffectPlanHash,
  launchdEntryTransitions,
  launchdPlanHash,
  launchdPlanVariant,
  launchdPlistBytesHash,
  loadLaunchdProcessTable,
  maximumLaunchdEffectJournalBytes,
  parseCanonicalLaunchdPlist,
  parseLaunchdLiveState,
  planLaunchdTransitions,
  sameLaunchdLiveState,
  validateLaunchdEffectJournal,
  validateLaunchdEffectJournalForPlan,
  validateLaunchdEffectPlan,
  validateLaunchdPlan,
  validateLaunchdPlanPreview,
} from "./launchd/index.js";
export type {
  LaunchdBootoutDependenciesV1,
  LaunchdBootoutEvidenceV1,
  LaunchdBootoutPortV1,
  LaunchdBootstrapPlistsV1,
  LaunchdCoordinatorOperationV1,
  LaunchdEffectBindingV1,
  LaunchdEffectDependenciesV1,
  LaunchdEffectJournalPhaseV1,
  LaunchdEffectJournalPortV1,
  LaunchdEffectJournalStoreDependenciesV1,
  LaunchdEffectJournalV1,
  LaunchdEffectObservationV1,
  LaunchdEffectPlanV1,
  LaunchdEffectPositionV1,
  LaunchdEffectTransitionV1,
  LaunchdEntryTransitionsV1,
  LaunchdManifestBindingV1,
  LaunchdManifestFileStateV1,
  LaunchdPlanEntryV1,
  LaunchdPlanV1,
  LaunchdPlanVariantV1,
  LaunchdAdmittedPlistV1,
  LaunchdPlistPortV1,
  LaunchdTransitionRequestV1,
  LifecycleFileBindingV1,
} from "./launchd/index.js";
