export {
  MacOsPlatformAdapter,
  MacOsPlatformDiscoveryError,
  MacOsPlatformTrustError,
  MacOsPlatformInputError,
  MacOsPlatformUnsupportedError,
} from "./macos.js";
export type {
  MacOsPlatformAdapterOptions,
  MacOsPlatformEnvironment,
} from "./macos.js";
export type {
  AgentDiscovery,
  AgentName,
  PlatformAdapter,
  PlatformFacts,
} from "./types.js";
export {
  MacOsRetainedRename,
  MacOsRetainedRenameRefusalError,
  MacOsRetainedRenameThirdStateError,
  MacOsRetainedRenameUnavailableError,
  SpawnRenameAtxRunner,
} from "./retained-rename.js";
export type {
  ExactNoReplaceRenameRequestV1,
  ExactRenameParentIdentityV1,
  MacOsRetainedRenameDependencies,
  RenameNoReplace,
  RenameAtxRunner,
  RenameAtxRunRequestV1,
  RenameAtxRunResultV1,
  RenameSameParentNoReplace,
} from "./retained-rename.js";
export {
  admitLauncherPlatformIdentity,
  LauncherBundleAdmission,
  LauncherBundleRecoveryRequiredError,
  LauncherPlatformUnsupportedError,
} from "./launcher/index.js";
export type {
  AdmittedReleaseBundleV1,
  LauncherBundleAdmissionRequestV1,
  LauncherGuardedReaderV1,
  LauncherPlatformIdentityV1,
} from "./launcher/index.js";
export { MacOsStableLockProvider } from "./stable-lock.js";
export type {
  MacOsStableLockDependencies,
  MacOsStableLockFileSystem,
} from "./stable-lock.js";
export {
  EX_TEMPFAIL,
  MacOsTransactionLockOperationalError,
  MacOsTransactionLockProvider,
  MacOsTransactionLockUnavailableError,
  SpawnLockfRunner,
} from "./transaction-lock.js";
export type { LockfResult, LockfRunner } from "./transaction-lock.js";
export {
  LAUNCHD_JOBS,
  LaunchdInputError,
  MAX_LAUNCHD_PLIST_BYTES,
  boundedCanonicalPlistXml,
  buildLaunchdPlanPreview,
  eligibleLaunchdJobs,
  encodeLaunchdPlist,
  generatedLabel,
  gitSyncEligible,
  launchdCalendarInterval,
  launchdGeneration,
  launchdGuiDomain,
  launchdJob,
  launchdLogPath,
  launchdPlistDictionary,
  launchdPlistPath,
  launchdPriorStateFingerprint,
  launchdStatusPath,
  parseGeneratedLabel,
  parseScheduleFlag,
  parseScheduledProductHome,
  reconcileAutomationSchedules,
  scheduledBaseArgv,
  scheduledProgramArguments,
} from "./launchd/index.js";
export type {
  BoundedCanonicalPlistXmlV1,
  ClosedLaunchdBaseLabelV1,
  GeneratedLaunchdLabelV1,
  LaunchdBaseArgvV1,
  LaunchdCalendarIntervalV1,
  LaunchdGeneratedServiceTargetV1,
  LaunchdGenerationProjectionV1,
  LaunchdGenerationV1,
  LaunchdGuiDomainV1,
  LaunchdJobDefinitionV1,
  LaunchdLiveStateV1,
  LaunchdObservedLabelV1,
  LaunchdObservedServiceTargetV1,
  LaunchdPlanOperationV1,
  LaunchdPlanPreviewEntryV1,
  LaunchdPlanPreviewV1,
  LaunchdPlistDictionaryV1,
  LaunchdPreviewRequestV1,
  LaunchdPriorJobStateV1,
  LaunchdProgramArgumentsV1,
  LaunchdScheduledProductHomeV1,
} from "./launchd/index.js";
export {
  LAUNCHD_PREVIEW_OBSERVATION_TABLE,
  LAUNCHD_PROCESS_PATH,
  LAUNCHD_SERVICE_ABSENT_EXIT,
  LaunchdDistributionUnsupportedError,
  LaunchdObserver,
  SUPPORTED_LAUNCHD_DISTRIBUTION,
  SUPPORTED_LAUNCHD_PROCESS_TABLE_TEMPLATE,
  admitLaunchdDistribution,
  deslotLaunchdProcessTable,
  expandLaunchdProcessTable,
  launchdObservationProcessTableHash,
  launchdProcessTableHash,
  launchdProcessTableTemplateHash,
  requireLaunchdMutationCertified,
} from "./launchd/index.js";
export type {
  LaunchdArgvSlotV1,
  LaunchdBootoutArgvV1,
  LaunchdBootstrapArgvV1,
  LaunchdCertificationV1,
  LaunchdDistributionRowV1,
  LaunchdEmptyDirectoryIdentityV1,
  LaunchdEmptyDirectoryObservationV1,
  LaunchdExecutableIdentityV1,
  LaunchdLiveObservationV1,
  LaunchdMutationIoProfileV1,
  LaunchdObservationDependenciesV1,
  LaunchdObservationJobV1,
  LaunchdObservationRequestV1,
  LaunchdObservedStateV1,
  LaunchdOperatingSystemV1,
  LaunchdPreviewObservationProcessTableV1,
  LaunchdProbeDomainArgvV1,
  LaunchdProbeServiceArgvV1,
  LaunchdProcessArgvV1,
  LaunchdProcessDirectoryIdentityV1,
  LaunchdProcessDirectorySlotV1,
  LaunchdProcessEnvironmentV1,
  LaunchdProcessIoProfileV1,
  LaunchdQueryIoProfileV1,
  LaunchdUnobservableReasonV1,
  ObservedLaunchdDistributionV1,
  SupportedLaunchdProcessTableTemplateV1,
  SupportedLaunchdProcessTableV1,
} from "./launchd/index.js";
