/**
 * The project instruction files `project init` writes, embedded rather than read from disk.
 *
 * The reviewable copy is `templates/project/` at the repository root, and
 * `project-template.test.ts` fails if the two ever differ, for the same reason
 * `brain-template.ts` embeds `templates/brain/`. Regenerate each `content` as
 * `JSON.stringify` of the file; never hand-edit one side alone.
 */
/** A flat file name and its UTF-8 content. */
export interface ProjectTemplateFile {
  readonly name: string;
  readonly content: string;
}

export const PROJECT_TEMPLATE_MAX_FILES = 8;
export const PROJECT_TEMPLATE_MAX_BYTES = 64 * 1024;
export const PROJECT_TEMPLATE: readonly ProjectTemplateFile[] = [
  {
    name: "AGENTS.md",
    content: "# <Project name>\n\n<!-- Include ONLY project-specific information. Communication style, shared code style,\n     workflow, and negative constraints come from the user-level rules; do not repeat them.\n     Test every line: \"Would deleting this make the agent produce errors?\" If not, remove it.\n     Domain knowledge needed only sometimes belongs in a project skill, not in this file.\n     Target: fewer than 100 lines. Keep _Context.md as the short navigation signpost, and\n     keep this file and CLAUDE.md in step when both exist. -->\n\n## Project purpose\n\n<!-- Two to four sentences: what it does, who it serves, UI language, and domain. -->\n\n## Commands\n\n```bash\n# Real dev, build, lint, type-check, test, and migration commands from the project manifest.\n```\n\n## Stack\n\n<!-- Technologies with versions, non-negotiable choices, and rejected tools with reasons. -->\n\n## Architecture\n\n<!-- Only non-obvious directories, data flow, and key patterns with file:line references.\n     Link to details under docs/ instead of duplicating them inline. -->\n\n## Project-specific conventions\n\n<!-- Naming, API patterns, and validation rules that DIFFER from the user-level rules.\n     API projects should be concrete: pagination default and maximum, cursor or offset,\n     the deprecation signal at sunset, the date format, and the error envelope. -->\n\n## Dependency policy\n\n<!-- Three to five lines: how fast critical and high security patches land, whether\n     applications pin exact versions, where a new dependency's rationale is recorded,\n     and which licenses need review before adding. -->\n\n## Decisions (ADR-lite)\n\n<!-- | date | decision | reason | — at most ten rows. Move older decisions to the\n     knowledge base with `developer-os capture`, and find them again with\n     `developer-os brain search`. This is the short \"why\"; full history lives in the\n     project's plans. -->\n\n## Anti-patterns (do NOT)\n\n<!-- Concrete project prohibitions with reasons. Record deliberate deferrals explicitly,\n     for example \"X is a deliberate DEFER, not a defect,\" so audits do not reopen them. -->\n\n## Documentation\n\n<!-- Link to docs/index.md or the equivalent. Sync rule: behavior change = docs update. -->\n",
  },
  {
    name: "CLAUDE.md",
    content: "# <Project name>\n\n<!-- Include ONLY project-specific information. Communication style, shared code style,\n     workflow, and negative constraints come from the user-level rules; do not repeat them.\n     Test every line: \"Would deleting this make the agent produce errors?\" If not, remove it.\n     Domain knowledge needed only sometimes belongs in a project skill, not in this file.\n     Target: fewer than 100 lines. Keep _Context.md as the short navigation signpost. -->\n\n## Project purpose\n\n<!-- Two to four sentences: what it does, who it serves, UI language, and domain. -->\n\n## Commands\n\n```bash\n# Real dev, build, lint, type-check, test, and migration commands from the project manifest.\n```\n\n## Stack\n\n<!-- Technologies with versions, non-negotiable choices, and rejected tools with reasons. -->\n\n## Architecture\n\n<!-- Only non-obvious directories, data flow, and key patterns with file:line references.\n     Link to details under docs/ instead of duplicating them inline. -->\n\n## Project-specific conventions\n\n<!-- Naming, API patterns, and validation rules that DIFFER from the user-level rules.\n     API projects should be concrete: pagination default and maximum, cursor or offset,\n     the deprecation signal at sunset, the date format, and the error envelope. -->\n\n## Dependency policy\n\n<!-- Three to five lines: how fast critical and high security patches land, whether\n     applications pin exact versions, where a new dependency's rationale is recorded,\n     and which licenses need review before adding. -->\n\n## Decisions (ADR-lite)\n\n<!-- | date | decision | reason | — at most ten rows. Move older decisions to the\n     knowledge base with `developer-os capture`, and find them again with\n     `developer-os brain search`. This is the short \"why\"; full history lives in the\n     project's plans. -->\n\n## Anti-patterns (do NOT)\n\n<!-- Concrete project prohibitions with reasons. Record deliberate deferrals explicitly,\n     for example \"X is a deliberate DEFER, not a defect,\" so audits do not reopen them. -->\n\n## Documentation\n\n<!-- Link to docs/index.md or the equivalent. Sync rule: behavior change = docs update. -->\n",
  },
  {
    name: "_Context.md",
    content: "# <Project name> — context\n\n<!-- A project navigation INDEX. It tells the agent what to read first and what to ignore\n     before touching code. Keep it at 25 lines or fewer: it is a signpost, not\n     documentation. Do not repeat the instruction files (AGENTS.md, CLAUDE.md). Keep only\n     \"where to look,\" hard boundaries, and current state. -->\n\n**Purpose:** <One or two sentences: what it does, for whom, stack, domain, and UI language when relevant.>\n\n**Read first:**\n- The instruction file (<exact section, for example Key Business Rules>)\n- <path to the core, glossary, or key module>\n\n**Ignore:** <dependency directories, build output, backups, and unrelated deployment directories; include a reason when non-obvious>\n\n**Hard rules:** <invariants whose violation breaks the project, such as server-side pricing,\na platform-free core, or the validation command required before a commit. Mark deliberate\ndeferrals as \"X is a deliberate DEFER, not a missing feature.\">\n\n**State as of <YYYY-MM-DD>:** <active, maintenance, or frozen; last real work; open items>\n\n<!-- FRESHNESS RULE: update \"State as of\" after every material session. A stale signpost\n     is worse than no signpost. -->\n",
  },
];
