import { createHash } from "node:crypto";
import { constants } from "node:fs";
import type { Stats } from "node:fs";
import type { FileHandle } from "node:fs/promises";
import { dirname, join } from "node:path";
import { EXIT_CODES } from "../result.js";
import { encodeCanonicalJson } from "../lifecycle/canonical-json.js";
import { admitCanonicalAbsolutePath, deriveBootstrapPayloadPath, deriveManifestPayloadPath, type BootstrapPayloadPathV1, type CanonicalAbsolutePathV1, type CanonicalPathEvidenceV1, type ManifestPayloadPathV1 } from "../update/paths.js";
import { parseLowerHexSha256, parseUInt64Decimal, type LowerHexSha256, type UInt64DecimalV1 } from "../update/scalars.js";
import type { ManifestAdmissionContextV1 } from "./types.js";
import { validateManifestBytes } from "./v2.js";

const MAX = 64 * 1024 * 1024;
const encoder = new TextEncoder();
export type ManifestParticipantIdV1 = string & { readonly __manifestParticipantIdV1: unique symbol };
export type FreshV2InitIdV1 = string & { readonly __freshV2InitIdV1: unique symbol };
export type ManifestMigrationIdV1 = string & { readonly __manifestMigrationIdV1: unique symbol };
export type LifecycleCoordinatorIdV1 = string & { readonly __lifecycleCoordinatorIdV1: unique symbol };
export interface BootstrapExpectedPayloadRefV1 { readonly kind: "bootstrap_expected"; readonly bootstrapId: FreshV2InitIdV1 | ManifestMigrationIdV1; readonly ordinal: number; readonly path: BootstrapPayloadPathV1; readonly hash: LowerHexSha256; readonly bytes: number; readonly mode: 0o600; }
export interface UpdateExpectedPayloadRefV1 { readonly kind: "update_expected"; readonly coordinatorId: LifecycleCoordinatorIdV1; readonly ordinal: number; readonly path: CanonicalAbsolutePathV1; readonly hash: LowerHexSha256; readonly bytes: number; readonly mode: 0o600; }
export type ManifestPayloadRefV1 = BootstrapExpectedPayloadRefV1 | (UpdateExpectedPayloadRefV1 & { readonly path: ManifestPayloadPathV1 });
export type ManifestBytesStateV1 = { readonly state: "absent" } | { readonly state: "present"; readonly hash: LowerHexSha256; readonly bytes: ManifestPayloadRefV1 | null; readonly ownerUid: number; readonly mode: 0o600; readonly nlink: 1; readonly size: UInt64DecimalV1; readonly dev: UInt64DecimalV1 | null; readonly ino: UInt64DecimalV1 | null; };
export interface ManifestExternalEffectRefV1 { readonly kind: "codex_registration" | "git" | "launchd"; readonly id: string; readonly planHash: LowerHexSha256; }
export type ManifestEnvelopeV1 = { readonly kind: "fresh_v2_init"; readonly id: FreshV2InitIdV1 } | { readonly kind: "v1_migration"; readonly id: ManifestMigrationIdV1 } | { readonly kind: "lifecycle"; readonly id: LifecycleCoordinatorIdV1 };
export interface ManifestStatePlanV1 { readonly schemaVersion: 1; readonly participantId: ManifestParticipantIdV1; readonly envelope: ManifestEnvelopeV1; readonly bindings: { readonly foundationTransactions: { readonly count: number; readonly orderedIdsHash: LowerHexSha256 }; readonly externalEffects: readonly ManifestExternalEffectRefV1[] }; readonly manifestPath: CanonicalAbsolutePathV1; readonly tombstonePath: CanonicalAbsolutePathV1; readonly before: ManifestBytesStateV1; readonly after: ManifestBytesStateV1; readonly maximumPlanBytes: number; readonly maximumJournalBytes: number; }
export interface ManifestPayloadIdentityV1 { readonly dev: UInt64DecimalV1; readonly ino: UInt64DecimalV1; }
export interface AdmittedManifestParticipantV1 { readonly envelope: ManifestEnvelopeV1; readonly participantId: ManifestParticipantIdV1; }
export interface ManifestStatePlanAdmissionContextV1 { readonly evidence: CanonicalPathEvidenceV1; readonly productHome: CanonicalAbsolutePathV1; readonly manifestPath: CanonicalAbsolutePathV1; readonly foundationTransactionIds: readonly string[]; readonly externalEffects: readonly ManifestExternalEffectRefV1[]; readonly admitParticipant: (envelope: unknown, participantId: unknown) => AdmittedManifestParticipantV1; readonly admitExternalEffect: (value: unknown) => ManifestExternalEffectRefV1; readonly bootstrapPayloadIdentity?: (value: BootstrapExpectedPayloadRefV1) => ManifestPayloadIdentityV1 | null; readonly updatePayloadIdentity?: (value: UpdateExpectedPayloadRefV1) => ManifestPayloadIdentityV1; }
export interface ManifestFileIdentityV1 { readonly hash: LowerHexSha256; readonly ownerUid: number; readonly mode: 0o600; readonly nlink: 1; readonly size: UInt64DecimalV1; readonly dev: UInt64DecimalV1; readonly ino: UInt64DecimalV1; }
export interface ManifestStateParticipantDependencies { readonly fs: { readonly lstat: (path: string) => Promise<Stats>; readonly open: (path: string, flags: number) => Promise<FileHandle>; }; readonly guardedMoveNoReplace: (source: CanonicalAbsolutePathV1, destination: CanonicalAbsolutePathV1, expected: ManifestFileIdentityV1) => Promise<void>; readonly guardedUnlinkExact: (path: CanonicalAbsolutePathV1, expected: ManifestFileIdentityV1) => Promise<void>; readonly admission: ManifestStatePlanAdmissionContextV1; readonly uid: number; readonly manifestAdmission?: ManifestAdmissionContextV1; }
export type ManifestParticipantObservationV1 = { readonly state: "before" | "preimage_preserved" | "applied" | "compensated"; };
export class ManifestStateParticipantError extends Error { readonly code = EXIT_CODES.recoveryRequired; constructor(message = "manifest direct-write state is malformed or conflicted") { super(message); this.name = "ManifestStateParticipantError"; } }
function fail(): never { throw new ManifestStateParticipantError(); }
function obj(value: unknown): Record<string, unknown> { if (typeof value !== "object" || value === null || Array.isArray(value)) fail(); return value as Record<string, unknown>; }
function keys(value: Record<string, unknown>, wanted: readonly string[]): void { const actual = Object.keys(value).sort(), ordered = [...wanted].sort(); if (actual.length !== ordered.length || actual.some((key, index) => key !== ordered[index])) fail(); }
function int(value: unknown, min: number, max: number): number { if (typeof value !== "number" || !Number.isSafeInteger(value) || value < min || value > max) fail(); return value; }
function sha(value: unknown): LowerHexSha256 { try { return parseLowerHexSha256(value); } catch { return fail(); } }
function u64(value: unknown): UInt64DecimalV1 { try { return parseUInt64Decimal(value); } catch { return fail(); } }
function eq(a: unknown, b: unknown): boolean { return JSON.stringify(a) === JSON.stringify(b); }
function foundation(ids: readonly string[]): LowerHexSha256 { return createHash("sha256").update("developer-os/manifest-foundation-bindings/v1\0").update(JSON.stringify(ids)).digest("hex") as LowerHexSha256; }
function payload(value: unknown, envelope: ManifestEnvelopeV1, context: ManifestStatePlanAdmissionContextV1, participantId: ManifestParticipantIdV1): ManifestPayloadRefV1 { const input = obj(value); if (input.kind === "update_expected") { keys(input, ["bytes", "coordinatorId", "hash", "kind", "mode", "ordinal", "path"]); if (envelope.kind !== "lifecycle" || input.coordinatorId !== envelope.id || input.mode !== 0o600 || context.updatePayloadIdentity === undefined) fail(); const ref = { kind: "update_expected" as const, coordinatorId: input.coordinatorId as LifecycleCoordinatorIdV1, ordinal: int(input.ordinal, 0, 1_099_999), path: admitCanonicalAbsolutePath(input.path, context.evidence), hash: sha(input.hash), bytes: int(input.bytes, 0, MAX), mode: 0o600 as const }; if (ref.path !== deriveManifestPayloadPath(context.productHome, ref.coordinatorId as never, participantId as never)) fail(); u64(context.updatePayloadIdentity(ref).dev); u64(context.updatePayloadIdentity(ref).ino); return ref as ManifestPayloadRefV1; } if (input.kind === "bootstrap_expected") { keys(input, ["bootstrapId", "bytes", "hash", "kind", "mode", "ordinal", "path"]); if (envelope.kind === "lifecycle" || input.bootstrapId !== envelope.id || input.mode !== 0o600) fail(); const ref = { kind: "bootstrap_expected" as const, bootstrapId: input.bootstrapId as FreshV2InitIdV1 | ManifestMigrationIdV1, ordinal: int(input.ordinal, 0, 999_999), path: admitCanonicalAbsolutePath(input.path, context.evidence) as BootstrapPayloadPathV1, hash: sha(input.hash), bytes: int(input.bytes, 0, MAX), mode: 0o600 as const }; if (ref.path !== deriveBootstrapPayloadPath(context.productHome, envelope.kind === "fresh_v2_init" ? "fresh_v2_init" : "v1_to_v2", ref.bootstrapId as never, ref.ordinal)) fail(); return ref; } return fail(); }
function state(value: unknown, role: "before" | "after", envelope: ManifestEnvelopeV1, context: ManifestStatePlanAdmissionContextV1, participantId: ManifestParticipantIdV1): ManifestBytesStateV1 { const input = obj(value); if (input.state === "absent") { keys(input, ["state"]); return { state: "absent" }; } keys(input, ["bytes", "dev", "hash", "ino", "mode", "nlink", "ownerUid", "size", "state"]); if (input.state !== "present" || input.mode !== 0o600 || input.nlink !== 1 || !Number.isSafeInteger(input.ownerUid) || (role === "before" && input.bytes !== null)) fail(); const nul = input.dev === null && input.ino === null; if ((input.dev === null) !== (input.ino === null) || (role === "before" && nul) || (role === "after" && (envelope.kind === "lifecycle" ? nul : !nul))) fail(); const result = { state: "present" as const, hash: sha(input.hash), bytes: input.bytes === null ? null : payload(input.bytes, envelope, context, participantId), ownerUid: input.ownerUid as number, mode: 0o600 as const, nlink: 1 as const, size: u64(input.size), dev: nul ? null : u64(input.dev), ino: nul ? null : u64(input.ino) }; if (role === "after") { if (result.bytes === null || result.bytes.hash !== result.hash || result.bytes.bytes !== Number(result.size)) fail(); if (result.bytes.kind === "update_expected") { const evidence = context.updatePayloadIdentity?.(result.bytes); if (evidence === undefined || evidence.dev !== result.dev || evidence.ino !== result.ino) fail(); } } return result; }
function effects(value: unknown, context: ManifestStatePlanAdmissionContextV1, envelope: ManifestEnvelopeV1): readonly ManifestExternalEffectRefV1[] { if (!Array.isArray(value) || value.length > 1 || (envelope.kind !== "lifecycle" && value.length !== 0)) fail(); const output = value.map((item) => { const input = obj(item); keys(input, ["id", "kind", "planHash"]); if (input.kind !== "codex_registration" && input.kind !== "git" && input.kind !== "launchd" || typeof input.id !== "string") fail(); const ref = { kind: input.kind, id: input.id, planHash: sha(input.planHash) } as ManifestExternalEffectRefV1; if (!eq(context.admitExternalEffect(ref), ref)) fail(); return ref; }); if (new Set(output.map((item) => `${item.kind}\0${item.id}`)).size !== output.length || !eq(output, context.externalEffects)) fail(); return output; }
export function validateManifestStatePlan(value: unknown, context: ManifestStatePlanAdmissionContextV1): ManifestStatePlanV1 { try { const input = obj(value); keys(input, ["after", "before", "bindings", "envelope", "manifestPath", "maximumJournalBytes", "maximumPlanBytes", "participantId", "schemaVersion", "tombstonePath"]); if (input.schemaVersion !== 1) fail(); const participant = context.admitParticipant(input.envelope, input.participantId); const manifestPath = admitCanonicalAbsolutePath(input.manifestPath, context.evidence); if (manifestPath !== context.manifestPath) fail(); const tombstonePath = admitCanonicalAbsolutePath(input.tombstonePath, context.evidence); if (tombstonePath !== join(dirname(manifestPath), `.installation-manifest.${participant.participantId}.json.tombstone`)) fail(); const binding = obj(input.bindings), tx = obj(binding.foundationTransactions); keys(binding, ["externalEffects", "foundationTransactions"]); keys(tx, ["count", "orderedIdsHash"]); const count = int(tx.count, 0, 1_000_000), orderedIdsHash = sha(tx.orderedIdsHash); if (count !== context.foundationTransactionIds.length || new Set(context.foundationTransactionIds).size !== count || orderedIdsHash !== foundation(context.foundationTransactionIds)) fail(); const before = state(input.before, "before", participant.envelope, context, participant.participantId), after = state(input.after, "after", participant.envelope, context, participant.participantId); const plan = { schemaVersion: 1 as const, participantId: participant.participantId, envelope: participant.envelope, bindings: { foundationTransactions: { count, orderedIdsHash }, externalEffects: effects(binding.externalEffects, context, participant.envelope) }, manifestPath, tombstonePath, before, after, maximumPlanBytes: int(input.maximumPlanBytes, 1, 16_777_216), maximumJournalBytes: int(input.maximumJournalBytes, 1, 1_048_576) }; if (encoder.encode(encodeCanonicalJson(plan as never)).byteLength > plan.maximumPlanBytes) fail(); return structuredClone(plan); } catch (error) { if (error instanceof ManifestStateParticipantError) throw error; return fail(); } }
type State = "missing" | "before" | "after" | "invalid";
export class ManifestStateParticipant { constructor(readonly dependencies: ManifestStateParticipantDependencies) {} async observe(plan: ManifestStatePlanV1): Promise<ManifestParticipantObservationV1> { const p = validateManifestStatePlan(plan, this.dependencies.admission), s = await this.inventory(p); if (Object.values(s).includes("invalid")) fail(); if (this.before(p, s)) return { state: "before" }; if (this.preimage(p, s)) return { state: "preimage_preserved" }; if (this.applied(p, s)) return { state: "applied" }; fail(); } async apply(plan: ManifestStatePlanV1): Promise<ManifestParticipantObservationV1> { const p = validateManifestStatePlan(plan, this.dependencies.admission), current = await this.observe(p); if (current.state === "applied") return current; if (p.before.state === "present" && current.state === "before") await this.move(p.manifestPath, p.tombstonePath, p.before); if (p.after.state === "present") { if (p.after.bytes === null) fail(); await this.move(p.after.bytes.path, p.manifestPath, p.after); } if (!this.applied(p, await this.inventory(p))) fail(); return { state: "applied" }; } async compensate(plan: ManifestStatePlanV1): Promise<ManifestParticipantObservationV1> { const p = validateManifestStatePlan(plan, this.dependencies.admission), current = await this.observe(p); if (current.state === "before") return { state: "compensated" }; if (p.after.state === "present") { if (p.after.bytes === null) fail(); await this.move(p.manifestPath, p.after.bytes.path, p.after); } if (p.before.state === "present") await this.move(p.tombstonePath, p.manifestPath, p.before); if (!(await this.observe(p)).state.includes("before")) fail(); return { state: "compensated" }; } async compact(plan: ManifestStatePlanV1): Promise<void> { const p = validateManifestStatePlan(plan, this.dependencies.admission); if (!this.applied(p, await this.inventory(p))) fail(); if (p.before.state === "present") try { await this.dependencies.guardedUnlinkExact(p.tombstonePath, this.id(p.before)); } catch { fail(); } }
  private async inventory(p: ManifestStatePlanV1): Promise<{ manifest: State; tombstone: State; payload: State }> { return { manifest: await this.file(p.manifestPath, p, "manifest"), tombstone: await this.file(p.tombstonePath, p, "tombstone"), payload: p.after.state === "present" && p.after.bytes !== null ? await this.file(p.after.bytes.path, p, "payload") : "missing" }; } private before(p: ManifestStatePlanV1, s: { manifest: State; tombstone: State; payload: State }): boolean { return s.manifest === (p.before.state === "present" ? "before" : "missing") && s.tombstone === "missing" && s.payload === (p.after.state === "present" ? "after" : "missing"); } private preimage(p: ManifestStatePlanV1, s: { manifest: State; tombstone: State; payload: State }): boolean { return p.before.state === "present" && s.manifest === "missing" && s.tombstone === "before" && s.payload === (p.after.state === "present" ? "after" : "missing"); } private applied(p: ManifestStatePlanV1, s: { manifest: State; tombstone: State; payload: State }): boolean { return s.manifest === (p.after.state === "present" ? "after" : "missing") && s.tombstone === (p.before.state === "present" ? "before" : "missing") && s.payload === "missing"; } private async move(source: CanonicalAbsolutePathV1, destination: CanonicalAbsolutePathV1, expected: Extract<ManifestBytesStateV1, { state: "present" }>): Promise<void> { try { await this.dependencies.guardedMoveNoReplace(source, destination, this.id(expected)); } catch { fail(); } } private id(s: Extract<ManifestBytesStateV1, { state: "present" }>): ManifestFileIdentityV1 { const evidence = s.dev === null ? s.bytes?.kind === "bootstrap_expected" ? this.dependencies.admission.bootstrapPayloadIdentity?.(s.bytes) ?? null : null : { dev: s.dev, ino: s.ino as UInt64DecimalV1 }; if (evidence === null) fail(); return { hash: s.hash, ownerUid: s.ownerUid, mode: s.mode, nlink: s.nlink, size: s.size, dev: evidence.dev, ino: evidence.ino }; }
  private async file(path: CanonicalAbsolutePathV1, p: ManifestStatePlanV1, role: "manifest" | "tombstone" | "payload"): Promise<State> { try { const listed = await this.dependencies.fs.lstat(path); if (!listed.isFile() || listed.isSymbolicLink() || listed.mode % 0o1000 !== 0o600 || listed.nlink !== 1 || listed.uid !== this.dependencies.uid || listed.size < 0 || listed.size > MAX) return "invalid"; const h = await this.dependencies.fs.open(path, constants.O_RDONLY | constants.O_NOFOLLOW); try { const opened = await h.stat(); if (opened.dev !== listed.dev || opened.ino !== listed.ino || opened.size !== listed.size) return "invalid"; const bytes = await this.read(h, opened.size), closed = await h.stat(), fresh = await this.dependencies.fs.lstat(path); if (closed.dev !== opened.dev || closed.ino !== opened.ino || closed.size !== opened.size || fresh.dev !== opened.dev || fresh.ino !== opened.ino || fresh.size !== opened.size) return "invalid"; const candidates = role === "tombstone" ? [p.before] : role === "payload" ? [p.after] : [p.before, p.after]; for (const expected of candidates) if (expected.state === "present" && this.match(expected, bytes, fresh)) { const decoded = validateManifestBytes(bytes, this.dependencies.manifestAdmission); if (expected === p.after && decoded.schemaVersion !== 2) return "invalid"; return expected === p.before ? "before" : "after"; } return "invalid"; } finally { await h.close(); } } catch (error) { if (typeof error === "object" && error !== null && "code" in error && ((error as { code?: unknown }).code === "ENOENT" || (error as { code?: unknown }).code === "ENOTDIR")) return "missing"; return "invalid"; } } private async read(h: FileHandle, size: number): Promise<Uint8Array> { const bytes = new Uint8Array(size); let at = 0; while (at < size) { const read = await h.read(bytes, at, size - at, at); if (read.bytesRead < 1) fail(); at += read.bytesRead; } const extra = new Uint8Array(1); if ((await h.read(extra, 0, 1, size)).bytesRead !== 0) fail(); return bytes; } private match(s: Extract<ManifestBytesStateV1, { state: "present" }>, bytes: Uint8Array, stat: Stats): boolean { const id = this.id(s); return createHash("sha256").update(bytes).digest("hex") === id.hash && stat.uid === id.ownerUid && stat.mode % 0o1000 === id.mode && stat.nlink === id.nlink && String(stat.size) === id.size && String(stat.dev) === id.dev && String(stat.ino) === id.ino; } }
