/**
 * Spec 1 §4.2's sanitized shadow configuration: the exact template and
 * projection records, the one Git-config byte renderer, instantiation and
 * de-slotting, and the owner-only shadow directory whose config and empty
 * hooks directory are bound by `dev`/`ino`. No Git process reads a real
 * source or destination config; it reads only these generated bytes.
 */
import { createHash, randomBytes } from "node:crypto";
import { constants, type BigIntStats } from "node:fs";
import * as nodeFs from "node:fs/promises";

import {
  hashCanonicalJson,
  parseCanonicalAbsolutePathText,
  parseFullBranchRef,
  parseNormalizedRemoteUrl,
  parseUInt64Decimal,
  type CanonicalAbsolutePathV1,
  type CanonicalJsonValue,
  type FullBranchRefV1,
  type LowerHexSha256,
  type NormalizedRemoteUrlV1,
  type UInt64DecimalV1,
} from "@developer-os/core";

import { SecurityRefusalError } from "../paths.js";
import { parseGitConfigQuotedPath } from "./process-table.js";
import type { GitConfigQuotedPathV1 } from "./types.js";

declare const opaqueGitLocalTokenV1: unique symbol;
declare const sanitizedGitShadowConfigBytesV1: unique symbol;

export type OpaqueGitLocalTokenV1 = string & { readonly [opaqueGitLocalTokenV1]: true };
export type SanitizedGitShadowConfigBytesV1 = string & { readonly [sanitizedGitShadowConfigBytesV1]: true };

export const OPAQUE_LOCAL_SELECTOR_PREFIX = "developer-os-local::";
export type SanitizedShadowRemoteUrlV1 = NormalizedRemoteUrlV1 | `developer-os-local::${string}`;

const TEMPLATE_DOMAIN = "developer-os:git-shadow-config-template:v1";
const PROJECTION_DOMAIN = "developer-os:git-shadow-config-projection:v1";
const BYTES_DOMAIN = "developer-os:git-shadow-config:v1";
const HEAD_MAX_BYTES = 4096;
const LOOSE_REF_MAX_BYTES = 41;
const encoder = new TextEncoder();

interface ShadowConfigFixedV1 {
  readonly schemaVersion: 1;
  readonly kind: "source" | "bare_destination";
  readonly commit: { readonly gpgSign: false };
  readonly tag: { readonly gpgSign: false };
  readonly gc: { readonly auto: 0 };
  readonly maintenance: { readonly auto: false };
  readonly http: { readonly proxy: ""; readonly followRedirects: false };
  readonly credential: { readonly helper: "" };
  readonly receive: null | {
    readonly unpackLimit: 0;
    readonly denyNonFastForwards: boolean;
    readonly denyDeletes: boolean;
  };
}

export interface SanitizedGitShadowConfigV1 extends ShadowConfigFixedV1 {
  readonly core: {
    readonly repositoryFormatVersion: 0;
    readonly fileMode: boolean;
    readonly bare: boolean;
    readonly hooksPath: GitConfigQuotedPathV1;
    readonly fsmonitor: false;
  };
  readonly remote: null | { readonly name: "developer-os"; readonly url: SanitizedShadowRemoteUrlV1 };
}

export interface SanitizedGitShadowConfigTemplateV1 extends ShadowConfigFixedV1 {
  readonly core: {
    readonly repositoryFormatVersion: 0;
    readonly fileMode: boolean;
    readonly bare: boolean;
    readonly hooksPath: { readonly slot: "hooks_directory" };
    readonly fsmonitor: false;
  };
  readonly remote: null | {
    readonly name: "developer-os";
    readonly url:
      | { readonly kind: "literal"; readonly value: NormalizedRemoteUrlV1 }
      | { readonly kind: "slot"; readonly slot: "opaque_local_selector" };
  };
}

/** The only two per-invocation values instantiation may place into a template. */
export interface SanitizedGitShadowSlotsV1 {
  readonly hooksDirectory: GitConfigQuotedPathV1;
  readonly opaqueLocalToken: OpaqueGitLocalTokenV1 | null;
}

export interface InstantiatedGitShadowConfigV1 {
  readonly template: SanitizedGitShadowConfigTemplateV1;
  readonly templateHash: LowerHexSha256;
  readonly configProjection: SanitizedGitShadowConfigV1;
  readonly configProjectionHash: LowerHexSha256;
  readonly bytes: SanitizedGitShadowConfigBytesV1;
  readonly configBytesHash: LowerHexSha256;
}

export interface GitShadowIdentityV1 {
  readonly dev: UInt64DecimalV1;
  readonly ino: UInt64DecimalV1;
}

interface MaterializedShadowV1<K extends "source" | "bare_destination"> extends InstantiatedGitShadowConfigV1 {
  readonly kind: K;
  readonly gitDir: GitConfigQuotedPathV1;
  readonly objectDirectory: CanonicalAbsolutePathV1;
  readonly configPath: CanonicalAbsolutePathV1;
  readonly configIdentity: GitShadowIdentityV1;
  readonly hooksPath: GitConfigQuotedPathV1;
  readonly hooksIdentity: GitShadowIdentityV1;
}

export type SanitizedGitShadowV1 = MaterializedShadowV1<"source">;
export type SanitizedBareDestinationShadowV1 = MaterializedShadowV1<"bare_destination">;

function fail(label: string): never {
  throw new Error(`invalid ${label}`);
}

function refuse(reason: string): never {
  throw new SecurityRefusalError(reason);
}

function exact(value: unknown, keys: readonly string[], label: string): Readonly<Record<string, unknown>> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) fail(label);
  const prototype = Object.getPrototypeOf(value) as object | null;
  if (prototype !== Object.prototype && prototype !== null) fail(label);
  const input = value as Readonly<Record<string, unknown>>;
  if (Object.keys(input).length !== keys.length || keys.some((key) => !Object.hasOwn(input, key))) fail(`${label}: keys`);
  return input;
}

function literal<T>(value: unknown, expected: T, label: string): T {
  if (value !== expected) fail(label);
  return expected;
}

function boolean(value: unknown, label: string): boolean {
  if (typeof value !== "boolean") fail(label);
  return value;
}

function sha256(bytes: Uint8Array): LowerHexSha256 {
  return createHash("sha256").update(bytes).digest("hex") as LowerHexSha256;
}

export function parseOpaqueGitLocalToken(value: unknown): OpaqueGitLocalTokenV1 {
  if (typeof value !== "string" || !/^[0-9a-f]{64}$/u.test(value)) fail("OpaqueGitLocalTokenV1");
  return value as OpaqueGitLocalTokenV1;
}

export function createOpaqueGitLocalToken(random: (size: number) => Uint8Array = randomBytes): OpaqueGitLocalTokenV1 {
  return parseOpaqueGitLocalToken(Buffer.from(random(32)).toString("hex"));
}

function parseNetworkRemoteUrl(value: unknown, label: string): NormalizedRemoteUrlV1 {
  for (const transport of ["https", "ssh"] as const) {
    try {
      return parseNormalizedRemoteUrl(value, transport);
    } catch {
      continue;
    }
  }
  return fail(label);
}

function parseShadowRemoteUrl(value: unknown, label: string): SanitizedShadowRemoteUrlV1 {
  if (typeof value === "string" && value.startsWith(OPAQUE_LOCAL_SELECTOR_PREFIX)) {
    parseOpaqueGitLocalToken(value.slice(OPAQUE_LOCAL_SELECTOR_PREFIX.length));
    return value as SanitizedShadowRemoteUrlV1;
  }
  return parseNetworkRemoteUrl(value, label);
}

const CONFIG_KEYS = ["schemaVersion", "kind", "core", "commit", "tag", "gc", "maintenance", "http", "credential", "remote", "receive"];
const CORE_KEYS = ["repositoryFormatVersion", "fileMode", "bare", "hooksPath", "fsmonitor"];

/** Every fixed section and the source/bare-destination arm invariants shared by template and projection. */
function validateFixed(
  input: Readonly<Record<string, unknown>>,
  label: string,
): { readonly fixed: ShadowConfigFixedV1; readonly core: Readonly<Record<string, unknown>>; readonly bare: boolean; readonly fileMode: boolean } {
  literal(input.schemaVersion, 1, `${label}.schemaVersion`);
  const kind = input.kind;
  if (kind !== "source" && kind !== "bare_destination") fail(`${label}.kind`);
  const core = exact(input.core, CORE_KEYS, `${label}.core`);
  literal(core.repositoryFormatVersion, 0, `${label}.core.repositoryFormatVersion`);
  literal(core.fsmonitor, false, `${label}.core.fsmonitor`);
  const fileMode = boolean(core.fileMode, `${label}.core.fileMode`);
  const bare = boolean(core.bare, `${label}.core.bare`);
  literal(exact(input.commit, ["gpgSign"], `${label}.commit`).gpgSign, false, `${label}.commit.gpgSign`);
  literal(exact(input.tag, ["gpgSign"], `${label}.tag`).gpgSign, false, `${label}.tag.gpgSign`);
  literal(exact(input.gc, ["auto"], `${label}.gc`).auto, 0, `${label}.gc.auto`);
  literal(exact(input.maintenance, ["auto"], `${label}.maintenance`).auto, false, `${label}.maintenance.auto`);
  const http = exact(input.http, ["proxy", "followRedirects"], `${label}.http`);
  literal(http.proxy, "", `${label}.http.proxy`);
  literal(http.followRedirects, false, `${label}.http.followRedirects`);
  literal(exact(input.credential, ["helper"], `${label}.credential`).helper, "", `${label}.credential.helper`);
  let receive: ShadowConfigFixedV1["receive"] = null;
  if (kind === "source") {
    if (bare || input.remote === null || input.receive !== null) fail(`${label}: source arm`);
  } else {
    if (!bare || input.remote !== null || input.receive === null) fail(`${label}: bare_destination arm`);
    const fields = exact(input.receive, ["unpackLimit", "denyNonFastForwards", "denyDeletes"], `${label}.receive`);
    literal(fields.unpackLimit, 0, `${label}.receive.unpackLimit`);
    receive = {
      unpackLimit: 0,
      denyNonFastForwards: boolean(fields.denyNonFastForwards, `${label}.receive.denyNonFastForwards`),
      denyDeletes: boolean(fields.denyDeletes, `${label}.receive.denyDeletes`),
    };
  }
  return {
    fixed: {
      schemaVersion: 1,
      kind,
      commit: { gpgSign: false },
      tag: { gpgSign: false },
      gc: { auto: 0 },
      maintenance: { auto: false },
      http: { proxy: "", followRedirects: false },
      credential: { helper: "" },
      receive,
    },
    core,
    bare,
    fileMode,
  };
}

export function validateShadowConfigTemplate(value: unknown): SanitizedGitShadowConfigTemplateV1 {
  const label = "SanitizedGitShadowConfigTemplateV1";
  const input = exact(value, CONFIG_KEYS, label);
  const { fixed, core, bare, fileMode } = validateFixed(input, label);
  literal(exact(core.hooksPath, ["slot"], `${label}.core.hooksPath`).slot, "hooks_directory", `${label}.core.hooksPath`);
  let remote: SanitizedGitShadowConfigTemplateV1["remote"] = null;
  if (input.remote !== null) {
    const fields = exact(input.remote, ["name", "url"], `${label}.remote`);
    literal(fields.name, "developer-os", `${label}.remote.name`);
    const url = fields.url as { readonly kind?: unknown } | null;
    if (typeof url === "object" && url !== null && url.kind === "slot") {
      literal(exact(url, ["kind", "slot"], `${label}.remote.url`).slot, "opaque_local_selector", `${label}.remote.url`);
      remote = { name: "developer-os", url: { kind: "slot", slot: "opaque_local_selector" } };
    } else {
      const text = exact(url, ["kind", "value"], `${label}.remote.url`);
      literal(text.kind, "literal", `${label}.remote.url.kind`);
      remote = { name: "developer-os", url: { kind: "literal", value: parseNetworkRemoteUrl(text.value, `${label}.remote.url`) } };
    }
  }
  return {
    ...fixed,
    core: { repositoryFormatVersion: 0, fileMode, bare, hooksPath: { slot: "hooks_directory" }, fsmonitor: false },
    remote,
  };
}

export function validateShadowConfig(value: unknown): SanitizedGitShadowConfigV1 {
  const label = "SanitizedGitShadowConfigV1";
  const input = exact(value, CONFIG_KEYS, label);
  const { fixed, core, bare, fileMode } = validateFixed(input, label);
  const hooksPath = parseGitConfigQuotedPath(core.hooksPath);
  let remote: SanitizedGitShadowConfigV1["remote"] = null;
  if (input.remote !== null) {
    const fields = exact(input.remote, ["name", "url"], `${label}.remote`);
    literal(fields.name, "developer-os", `${label}.remote.name`);
    remote = { name: "developer-os", url: parseShadowRemoteUrl(fields.url, `${label}.remote.url`) };
  }
  return { ...fixed, core: { repositoryFormatVersion: 0, fileMode, bare, hooksPath, fsmonitor: false }, remote };
}

export function hashShadowConfigTemplate(template: SanitizedGitShadowConfigTemplateV1): LowerHexSha256 {
  return hashCanonicalJson(TEMPLATE_DOMAIN, validateShadowConfigTemplate(template) as unknown as CanonicalJsonValue);
}

export function hashShadowConfigProjection(projection: SanitizedGitShadowConfigV1): LowerHexSha256 {
  return hashCanonicalJson(PROJECTION_DOMAIN, validateShadowConfig(projection) as unknown as CanonicalJsonValue);
}

export function hashShadowConfig(bytes: SanitizedGitShadowConfigBytesV1 | Uint8Array): LowerHexSha256 {
  const body = typeof bytes === "string" ? encoder.encode(bytes) : bytes;
  return createHash("sha256").update(`${BYTES_DOMAIN}\0`, "ascii").update(body).digest("hex") as LowerHexSha256;
}

/** The sole escape grammar: each backslash doubled, each double quote preceded by one backslash. */
export function renderGitConfigQuoted(value: string): string {
  for (const character of value) {
    const codePoint = character.codePointAt(0) as number;
    if (codePoint <= 0x1f || (codePoint >= 0x7f && codePoint <= 0x9f) || codePoint === 0x2028 || codePoint === 0x2029) {
      fail("GitConfigQuotedValue");
    }
  }
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

/** Spec §4.2's exact bytes: fixed section and key order, one HT, ` =`, optional ` value`, LF after every line. */
export function renderShadowConfig(projection: SanitizedGitShadowConfigV1): SanitizedGitShadowConfigBytesV1 {
  const config = validateShadowConfig(projection);
  const lines: string[] = [];
  const section = (header: string, entries: readonly (readonly [string, string])[]): void => {
    lines.push(header);
    for (const [key, value] of entries) lines.push(value === "" ? `\t${key} =` : `\t${key} = ${value}`);
  };
  section("[core]", [
    ["repositoryformatversion", "0"],
    ["filemode", String(config.core.fileMode)],
    ["bare", String(config.core.bare)],
    ["hooksPath", renderGitConfigQuoted(config.core.hooksPath)],
    ["fsmonitor", "false"],
  ]);
  section("[commit]", [["gpgSign", "false"]]);
  section("[tag]", [["gpgSign", "false"]]);
  section("[gc]", [["auto", "0"]]);
  section("[maintenance]", [["auto", "false"]]);
  section("[http]", [
    ["proxy", ""],
    ["followRedirects", "false"],
  ]);
  section("[credential]", [["helper", ""]]);
  if (config.remote !== null) section('[remote "developer-os"]', [["url", renderGitConfigQuoted(config.remote.url)]]);
  if (config.receive !== null) {
    section("[receive]", [
      ["unpackLimit", "0"],
      ["denyNonFastForwards", String(config.receive.denyNonFastForwards)],
      ["denyDeletes", String(config.receive.denyDeletes)],
    ]);
  }
  return `${lines.join("\n")}\n` as SanitizedGitShadowConfigBytesV1;
}

/** Replaces exactly the hooks path and, for a local source, the selector; nothing else can vary. */
export function deslotShadowConfig(projection: SanitizedGitShadowConfigV1): SanitizedGitShadowConfigTemplateV1 {
  const config = validateShadowConfig(projection);
  const url = config.remote?.url;
  const remote: SanitizedGitShadowConfigTemplateV1["remote"] =
    url === undefined
      ? null
      : {
          name: "developer-os",
          url: url.startsWith(OPAQUE_LOCAL_SELECTOR_PREFIX)
            ? { kind: "slot", slot: "opaque_local_selector" }
            : { kind: "literal", value: url as NormalizedRemoteUrlV1 },
        };
  return validateShadowConfigTemplate({ ...config, core: { ...config.core, hooksPath: { slot: "hooks_directory" } }, remote });
}

export function instantiateShadowConfig(
  template: SanitizedGitShadowConfigTemplateV1,
  slots: SanitizedGitShadowSlotsV1,
): InstantiatedGitShadowConfigV1 {
  const checked = validateShadowConfigTemplate(template);
  const selector = checked.remote?.url.kind === "slot";
  if (selector !== (slots.opaqueLocalToken !== null)) refuse("git_shadow_slot_mismatch");
  const remote: SanitizedGitShadowConfigV1["remote"] =
    checked.remote === null
      ? null
      : {
          name: "developer-os",
          url:
            checked.remote.url.kind === "literal"
              ? checked.remote.url.value
              : `${OPAQUE_LOCAL_SELECTOR_PREFIX}${parseOpaqueGitLocalToken(slots.opaqueLocalToken)}`,
        };
  const configProjection = validateShadowConfig({
    ...checked,
    core: { ...checked.core, hooksPath: parseGitConfigQuotedPath(slots.hooksDirectory) },
    remote,
  });
  const templateHash = hashShadowConfigTemplate(checked);
  if (hashShadowConfigTemplate(deslotShadowConfig(configProjection)) !== templateHash) refuse("git_shadow_template_mismatch");
  const bytes = renderShadowConfig(configProjection);
  return {
    template: checked,
    templateHash,
    configProjection,
    configProjectionHash: hashShadowConfigProjection(configProjection),
    bytes,
    configBytesHash: hashShadowConfig(bytes),
  };
}

/**
 * A retry re-instantiates against the persisted template hash alone; a
 * concrete projection that does not de-slot to it is recovery-required and
 * never falls back to a newly calculated config.
 */
export function bindShadowConfigToTemplate(
  persistedTemplateHash: LowerHexSha256,
  template: SanitizedGitShadowConfigTemplateV1,
  slots: SanitizedGitShadowSlotsV1,
): InstantiatedGitShadowConfigV1 {
  const instance = instantiateShadowConfig(template, slots);
  if (instance.templateHash !== persistedTemplateHash) refuse("git_shadow_template_mismatch");
  return instance;
}

export interface GitShadowSnapshotRefV1 {
  readonly ref: FullBranchRefV1;
  readonly bytes: Uint8Array;
}

export interface SanitizedGitShadowRequestV1 {
  /** Must not exist yet; its parent is the invocation's private owner-only quarantine. */
  readonly gitDir: CanonicalAbsolutePathV1;
  readonly template: SanitizedGitShadowConfigTemplateV1;
  readonly opaqueLocalToken: OpaqueGitLocalTokenV1 | null;
  readonly head: Uint8Array;
  readonly refs: readonly GitShadowSnapshotRefV1[];
  readonly effectiveUid: number;
}

const CREATE_FLAGS = constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY | constants.O_NOFOLLOW;
const READ_FLAGS = constants.O_RDONLY | constants.O_NOFOLLOW;

function identityOf(stats: BigIntStats): GitShadowIdentityV1 {
  return { dev: parseUInt64Decimal(stats.dev.toString(10)), ino: parseUInt64Decimal(stats.ino.toString(10)) };
}

function errorCode(error: unknown): string {
  return error !== null && typeof error === "object" && "code" in error ? String(error.code) : "";
}

async function makeDirectory(path: string, effectiveUid: number): Promise<GitShadowIdentityV1> {
  try {
    await nodeFs.mkdir(path, { mode: 0o700 });
  } catch (error) {
    if (errorCode(error) === "EEXIST") refuse("git_shadow_path_exists");
    throw error;
  }
  const stats = await nodeFs.lstat(path, { bigint: true });
  if (!stats.isDirectory() || Number(stats.uid) !== effectiveUid || Number(stats.mode & 0o777n) !== 0o700) refuse("git_shadow_postimage");
  return identityOf(stats);
}

async function writeExclusive(path: string, bytes: Uint8Array, effectiveUid: number): Promise<GitShadowIdentityV1> {
  let handle: nodeFs.FileHandle;
  try {
    handle = await nodeFs.open(path, CREATE_FLAGS, 0o600);
  } catch (error) {
    if (errorCode(error) === "EEXIST" || errorCode(error) === "ELOOP") refuse("git_shadow_path_exists");
    throw error;
  }
  try {
    const before = await handle.stat({ bigint: true });
    if (!before.isFile() || Number(before.uid) !== effectiveUid || Number(before.mode & 0o777n) !== 0o600 || before.nlink !== 1n) {
      refuse("git_shadow_postimage");
    }
    let offset = 0;
    while (offset < bytes.byteLength) {
      const { bytesWritten } = await handle.write(bytes, offset, bytes.byteLength - offset, null);
      offset += bytesWritten;
    }
    await handle.sync();
    return identityOf(before);
  } finally {
    await handle.close();
  }
}

async function readGuarded(path: string, maximumBytes: number): Promise<{ readonly stats: BigIntStats; readonly bytes: Uint8Array }> {
  const handle = await nodeFs.open(path, READ_FLAGS);
  try {
    const stats = await handle.stat({ bigint: true });
    if (!stats.isFile() || stats.size > BigInt(maximumBytes)) refuse("git_shadow_postimage");
    const buffer = new Uint8Array(maximumBytes + 1);
    let length = 0;
    for (;;) {
      const { bytesRead } = await handle.read(buffer, length, buffer.byteLength - length, null);
      if (bytesRead === 0) break;
      length += bytesRead;
      if (length > maximumBytes) refuse("git_shadow_postimage");
    }
    return { stats, bytes: buffer.subarray(0, length) };
  } finally {
    await handle.close();
  }
}

function assertSnapshot(request: SanitizedGitShadowRequestV1): void {
  if (request.head.byteLength < 1 || request.head.byteLength > HEAD_MAX_BYTES) refuse("git_shadow_snapshot_bounds");
  const seen = new Set<string>();
  for (const entry of request.refs) {
    parseFullBranchRef(entry.ref);
    if (seen.has(entry.ref) || entry.bytes.byteLength !== LOOSE_REF_MAX_BYTES) refuse("git_shadow_snapshot_bounds");
    seen.add(entry.ref);
  }
}

/**
 * Creates one owner-only shadow Git directory: generated config (0600), an
 * empty hooks directory (0700), a quarantine object directory, and the
 * validated `HEAD`/loose-ref snapshots. Every path is created exclusively
 * inside a fresh directory, then re-read and bound by identity before return.
 */
async function materializeShadow<K extends "source" | "bare_destination">(
  kind: K,
  request: SanitizedGitShadowRequestV1,
): Promise<MaterializedShadowV1<K>> {
  const template = validateShadowConfigTemplate(request.template);
  if (template.kind !== kind) refuse("git_shadow_kind_mismatch");
  assertSnapshot(request);
  const gitDir = parseGitConfigQuotedPath(request.gitDir);
  const hooksPath = parseGitConfigQuotedPath(`${gitDir}/hooks`);
  const instance = instantiateShadowConfig(template, { hooksDirectory: hooksPath, opaqueLocalToken: request.opaqueLocalToken });

  await makeDirectory(gitDir, request.effectiveUid);
  const hooksIdentity = await makeDirectory(hooksPath, request.effectiveUid);
  const objectDirectory = parseCanonicalAbsolutePathText(`${gitDir}/objects`);
  await makeDirectory(objectDirectory, request.effectiveUid);
  await makeDirectory(`${objectDirectory}/info`, request.effectiveUid);
  await makeDirectory(`${objectDirectory}/pack`, request.effectiveUid);
  await makeDirectory(`${gitDir}/refs`, request.effectiveUid);
  await makeDirectory(`${gitDir}/refs/heads`, request.effectiveUid);
  await makeDirectory(`${gitDir}/refs/tags`, request.effectiveUid);
  await writeExclusive(`${gitDir}/HEAD`, request.head, request.effectiveUid);
  const created = new Set<string>();
  for (const entry of request.refs) {
    const segments = entry.ref.split("/");
    for (let depth = 3; depth < segments.length; depth += 1) {
      const directory = `${gitDir}/${segments.slice(0, depth).join("/")}`;
      if (created.has(directory)) continue;
      await makeDirectory(directory, request.effectiveUid);
      created.add(directory);
    }
    await writeExclusive(`${gitDir}/${entry.ref}`, entry.bytes, request.effectiveUid);
  }
  const configPath = parseCanonicalAbsolutePathText(`${gitDir}/config`);
  const configIdentity = await writeExclusive(configPath, encoder.encode(instance.bytes), request.effectiveUid);

  const shadow: MaterializedShadowV1<K> = {
    ...instance,
    kind,
    gitDir,
    objectDirectory,
    configPath,
    configIdentity,
    hooksPath,
    hooksIdentity,
  };
  await verifySanitizedGitShadow(shadow, request.effectiveUid);
  return shadow;
}

export function materializeSanitizedGitShadow(request: SanitizedGitShadowRequestV1): Promise<SanitizedGitShadowV1> {
  return materializeShadow("source", request);
}

export function materializeSanitizedBareDestinationShadow(
  request: SanitizedGitShadowRequestV1,
): Promise<SanitizedBareDestinationShadowV1> {
  return materializeShadow("bare_destination", request);
}

/**
 * The supervisor's pre-admission check: guarded-reopen the config, require
 * its identity, single link, mode and exact bytes, and prove the
 * identity-matching hooks directory empty.
 */
export async function verifySanitizedGitShadow(
  shadow: MaterializedShadowV1<"source" | "bare_destination">,
  effectiveUid: number,
): Promise<void> {
  const configLimit = encoder.encode(shadow.bytes).byteLength;
  const { stats, bytes } = await readGuarded(shadow.configPath, configLimit);
  const identity = identityOf(stats);
  if (
    identity.dev !== shadow.configIdentity.dev ||
    identity.ino !== shadow.configIdentity.ino ||
    Number(stats.uid) !== effectiveUid ||
    Number(stats.mode & 0o777n) !== 0o600 ||
    stats.nlink !== 1n ||
    hashShadowConfig(bytes) !== shadow.configBytesHash ||
    sha256(bytes) !== sha256(encoder.encode(shadow.bytes))
  ) {
    refuse("git_shadow_config_changed");
  }
  const hooks = await nodeFs.lstat(shadow.hooksPath, { bigint: true });
  const hooksIdentity = identityOf(hooks);
  if (
    !hooks.isDirectory() ||
    hooksIdentity.dev !== shadow.hooksIdentity.dev ||
    hooksIdentity.ino !== shadow.hooksIdentity.ino ||
    Number(hooks.uid) !== effectiveUid ||
    Number(hooks.mode & 0o777n) !== 0o700 ||
    (await nodeFs.readdir(shadow.hooksPath)).length !== 0
  ) {
    refuse("git_shadow_hooks_changed");
  }
  if (hashShadowConfigProjection(shadow.configProjection) !== shadow.configProjectionHash) refuse("git_shadow_config_changed");
}
